version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "liczyrzepa-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q1feq26vowvm"
s3_prefix = "liczyrzepa-api"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
